version: '3'
services:
  user:
    image: user
    build:
      context: ../User/Dockerfile
    ports:
      - "3001:3001"
    command: node server.js

  cart:
    image: ../Cart/Dockerfile
    ports:
      - "3003:3003"
    command: node server.js  

  product:
    image: ../Product/Dockerfile
    ports:
      - "3002:3002"
    command: node server.js
    
