version: '3'
services:
  user_service:
    container_name: user_service
    build:
      context: ./User
    ports:
      - "9001:9001"
    env_file:
      - .env
    command: npm run start
    networks:
      - app-network
  cart_service:
    container_name: cart_service
    build:
      context: ./Cart
    ports:
      - "9003:9003"
    env_file:
      - .env
    command: npm run start 
    networks:
      - app-network

  product_service:
    container_name: product_service
    build:
      context: ./Product
    ports:
      - "9000:9000"
    command: npm run start
    env_file:
      - .env
    networks:
      - app-network
  front-end:
    container_name: front-end
    build:
      context: ./front-end
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: npm run dev
    networks:
      - app-network
networks:
  app-network:
    external: true
